[versions]
#navigation
nav_version = "2.3.5"
core_ktx_version = "1.7.0"
appcompat_version = "1.4.0"
material_version = "1.4.0"
constraintlayout_version = "2.1.2"

[libraries]
#navigation
navigation-fragment = {module = "androidx.navigation:navigation-fragment", version.ref = "nav_version"}

#main
core_ktx = {module = "androidx.core:core-ktx", version.ref = "core_ktx_version"}
appcompat = {module = "androidx.appcompat:appcompat", version.ref = "appcompat_version"}
material = {module = "com.google.android.material:material", version.ref = "material_version"}

constraintlayout = {module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout_version"}

[bundles]
main = ["core_ktx", "appcompat", "material"]
